# Generated by Django 5.1.6 on 2025-03-06 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome completo')),
                ('type', models.CharField(choices=[('personal', 'Pessoal'), ('business', 'Empresa')], default='personal', max_length=20, verbose_name='Tipo de conta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Nome da Empresa')),
                ('company_registration', models.CharField(blank=True, max_length=50, verbose_name='CNPJ/NIF')),
                ('company_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Empresa')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Setor de Atuação')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
